1 集成框架/XieCan.AspMVC.Web/Areas/Admin/Controllers/ArticleTypeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using XieCan.AspMVC.Mapper;
using XieCan.AspMVC.Models;
using XieCan.AspMVC.ViewModels;

namespace XieCan.AspMVC.Web.Areas.Admin.Controllers
{
    public class ArticleTypeController : BaseController
    {
        // GET: Admin/ArticleType
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Insert()
        {
            return PartialView();
        }

        public ActionResult Update(string id)
        {
            var result = ArticleTypeService.Find(new System.Guid(id));
            return PartialView(result.Data.MapTo<ArticleTypeUpdateViewModel>());
        }

        public ActionResult Detail(string id)
        {
            var result = ArticleTypeService.Find(new System.Guid(id));
            return PartialView(result.Data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ArticleTypeUpdateViewModel model)
        {
            ArticleTypeService.Update("Name", model.MapTo<ArticleTypeModel>());
            var result = ArticleService.SaveChanges();
            return Json(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(ArticleTypeInsertViewModel model)
        {
            ArticleTypeService.Insert(model.MapTo<ArticleTypeModel>());
            var result = ArticleService.SaveChanges();
            return Json(result);
        }

        [HttpPost]
        public ActionResult Delete(params string[] ids)
        {
            ArticleTypeService.Delete(ids);
            var result = ArticleService.SaveChanges();
            return Json(result);
        }

        public ActionResult Select(long pageIndex = 1, int pageSize = 10)
        {
            var result = ArticleTypeService.Select(p => true, p => p.CreateTime, out long rows, out long pages, isAsc: false, pageIndex: pageIndex, pageSize: pageSize);
            if (result.Success)
            {
                var list = result.Data.ToList().MapTo<ArticleTypeSelectViewModel>();
                return Json(new { rows = list, total = rows }, JsonRequestBehavior.AllowGet);
            }
            return Json(result.Message, JsonRequestBehavior.AllowGet);
        }
    }
}

1 集成框架/XieCan.AspMVC.Web/Areas/Admin/Controllers/BootstrapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace XieCan.AspMVC.Web.Areas.Admin.Controllers
{
    public class BootstrapController : Controller
    {
        // GET: Admin/Bootstrap
        public ActionResult Index()
        {
            return View();
        }
    }
}

1 集成框架/XieCan.AspMVC.Web/Areas/Admin/Controllers/VoiceController.cs
using System.Web.Mvc;

namespace XieCan.AspMVC.Web.Areas.Admin.Controllers
{
    public class VoiceController : BaseController
    {
        // GET: Admin/Voice
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(string name, string content)
        {
            return View();
        }
    }
}

1 集成框架/XieCan.AspMVC.Web/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_Root.cshtml";
}

@section styles{
    @RenderSection("styles", required: false)
}

@Html.Partial("_LeftMenu")
<div class="content-wrapper">
    <div class="container-fluid">
        @RenderBody()
    </div>
</div>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        谢灿软件工作室
    </div>
    <strong>Copyright &copy; 2014-@DateTime.Now.Year</strong> All rights reserved.
</footer>
@Html.Partial("_ControlSidebar")

@section scripts{
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(function () {
            $("body").removeClass("layout-top-nav");
        })
    </script>
}  

1 集成框架/XieCan.AspMVC.Web/Areas/Admin/Views/Shared/_LeftMenu.cshtml
@{
    Layout = null;
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="@Url.Content("~/Content/log.png")" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>谢灿软件工作室</p>
                <a href="#"><i class="fa fa-circle text-success"></i>我们一直都在！</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="key" class="form-control" placeholder="请输入关键字" />
                <span class="input-group-btn">
                    <button type='submit' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="#"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-files-o"></i>
                    <span>Layout Options</span>
                    <span class="pull-right-container">
                        <span class="label label-primary pull-right">4</span>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Boxed</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Fixed</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-th"></i> <span>Widgets</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-green">new</small>
                    </span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> ChartJS</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>UI Elements</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> General</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Sliders</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Forms</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> General Elements</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Tables</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-calendar"></i> <span>Calendar</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-red">3</small>
                        <small class="label pull-right bg-blue">17</small>
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <span class="pull-right-container">
                        <small class="label pull-right bg-yellow">12</small>
                        <small class="label pull-right bg-green">16</small>
                        <small class="label pull-right bg-red">5</small>
                    </span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Examples</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Invoice</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Profile</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Login</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Register</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Pace Page</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Multilevel</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Level One
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-circle-o"></i> Level Two
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                </ul>
            </li>
            <li><a href="#"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
            <li class="header">插件使用案例</li>
            <li><a href="@Url.Action("Index","Home")"><i class="fa fa-server text-red"></i> <span>服务器状态</span></a></li>
            <li><a href="@Url.Action("Add","Voice")"><i class="fa fa-circle-o text-yellow"></i> <span>在线编辑器</span></a></li>
            <li><a href="@Url.Action("Index","Bootstrap")"><i class="fa fa-circle-o text-aqua"></i> <span>Bootstrap-Models</span></a></li>
            <li><a href="@Url.Action("Index","ArticleType")"><i class="fa fa-circle-o text-bold"></i> <span>Bootstrap-table</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

1 集成框架/XieCan.AspMVC.Web/Areas/Admin/Views/Shared/_TopMenu.cshtml
@{
    ViewBag.Layout = null;
}

<header class="main-header">
    <!-- Logo -->
    <a href="@Url.Action("Index","Home",new { area=""})" class="logo"><b>谢灿软件</b>工作室</a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @Html.Partial("_MessageMenu")
                @Html.Partial("_NotificationMenu")
                @Html.Partial("_TaskMenu")
                @Html.Partial("_UserMenu")
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>